name: Code Quality

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - "*"

jobs:
  Formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Formatting
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_SNAKEMAKE_SNAKEFMT: true
          VALIDATE_SNAKEMAKE_LINT: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_MARKDOWN: true
